// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjv0YC8f-mwtpsBvhKkPW-CSK6na4EenI',
    appId: '1:1089270098826:web:7b283573e2107049ae7673',
    messagingSenderId: '1089270098826',
    projectId: 'calc-firebase-login',
    authDomain: 'calc-firebase-login.firebaseapp.com',
    storageBucket: 'calc-firebase-login.appspot.com',
    measurementId: 'G-YW7FGJL10Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQXj1bRNA5A7d0DCWd1RPspEyJVnsido',
    appId: '1:1089270098826:android:6ff313ce876775f2ae7673',
    messagingSenderId: '1089270098826',
    projectId: 'calc-firebase-login',
    storageBucket: 'calc-firebase-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLuAVV0Upkq8tOKnWv1sxz5hcVygUsGps',
    appId: '1:1089270098826:ios:365c65af2c626b6eae7673',
    messagingSenderId: '1089270098826',
    projectId: 'calc-firebase-login',
    storageBucket: 'calc-firebase-login.appspot.com',
    iosBundleId: 'com.example.calcFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLuAVV0Upkq8tOKnWv1sxz5hcVygUsGps',
    appId: '1:1089270098826:ios:365c65af2c626b6eae7673',
    messagingSenderId: '1089270098826',
    projectId: 'calc-firebase-login',
    storageBucket: 'calc-firebase-login.appspot.com',
    iosBundleId: 'com.example.calcFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjv0YC8f-mwtpsBvhKkPW-CSK6na4EenI',
    appId: '1:1089270098826:web:e9006d8a7054ef56ae7673',
    messagingSenderId: '1089270098826',
    projectId: 'calc-firebase-login',
    authDomain: 'calc-firebase-login.firebaseapp.com',
    storageBucket: 'calc-firebase-login.appspot.com',
    measurementId: 'G-Z73HW2ZXHW',
  );
}
